name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        code:
          - Run
          - RunFixedBoundary

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.code }}"
    runs-on: ubuntu-latest

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=ci" >> $GITHUB_ENV

    - name: Configure
      working-directory: ${{ matrix.code }}
      run: cmake -Bbuild

    - name: Compile
      working-directory: ${{ matrix.code }}/build
      run: make
