name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master

jobs:

  standard:

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.code }}
    runs-on: ubuntu-latest

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=0.0" >> $GITHUB_ENV

    - name: Install module
      run: python -m pip install . -vv

    - name: Install styles
      run: python -c "import GooseMPL; GooseMPL.copy_style()"

    - name: Run tests
      run: |
        python tests/slurm.py
        python tests/FixedLever.py
        python tests/tag.py
